### ISSUE TITLE
Policy_and_Layers[.wip] folder

### ISSUE THREAD

**Issue by cutrez** [mybasementcloud/R8x-export-import-api-scripts#6]
Hello @mybasementcloud :
Thank you for your contribution.
I cannot find the folder called Policy_and_Layers[.wip].
Are scripts focused on policies operatios into another different folder?
Thank you very much.

**Comment by mybasementcloud** [comment]
Hello,
So the R8x-export-import-api-scripts currently only handles objects, since policies and layers are much more complex set of data to export to CSV for actual re-import utilization.  Thus the content that lives in Policy_and_Layers.[wip] is actually covered in different project with it's own specific work, and found here:  https://github.com/mybasementcloud/R8X-API-scripts-4-policy-import-export
Given that limitations to time and availability, more effort is still flowing into the objects export, since policy and layer export/import is challenging and not as high on my requirement list currently.
The reference in documentation is for completeness, since there are overlaps in utilization of certain script elements planned for the future, as well as true common elements, like the tools folder, etc.
Best Regards

**Comment by cutrez** [comment]
OK, thank you very much @mybasementcloud .
